spring:
  application:
    name: sms-service
    version: 1.0.0

server:
  port: 8083
  servlet:
    context-path: /api/v1

jwt:
  secret: ${JWT_SECRET}

twilio:
  account:
    sid: ${TWILIO_ACCOUNT_SID}
  auth:
    token: ${TWILIO_AUTH_TOKEN}
  phone:
    number: ${TWILIO_PHONE_NUMBER}
