jwt:
  secret: ${JWT_SECRET}

server:
  port: 8082
  servlet:
    context-path: /api/v1

spring:
  application:
    name: plazoleta-microservice
    version: 1.0.0

  datasource:
    url: jdbc:mysql://localhost/plazoleta
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.yourpackage.clients: DEBUG
    feign.Client: DEBUG
    feign.Logger: DEBUG

traceability:
  service:
    url: localhost:8084/api/v1

sms:
  service:
    url: localhost:8083/api/v1

user:
  service:
    url: localhost:8081/api/v1

feign:
  client:
    config:
      default:
        loggerLevel: FULL